// AUTH
export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED'
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_SUCCEDED = 'LOGIN_SUCCEDED'

// PROJECTS
export const PROJECT_LIST_REQUESTED = 'PROJECT_LIST_REQUESTED'
export const PROJECT_LIST_FETCHED = 'PROJECT_LIST_FETCHED'
export const PROJECT_LIST_FAILED = 'PROJECT_LIST_FAILED'

