// AUTH
export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED'
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_SUCCEDED = 'LOGIN_SUCCEDED'

// PROJECTS
export const PROJECT_LIST_REQUESTED = 'PROJECT_LIST_REQUESTED'
export const PROJECT_LIST_FETCHED = 'PROJECT_LIST_FETCHED'
export const PROJECT_LIST_FAILED = 'PROJECT_LIST_FAILED'

// FEATURES
export const FEATURE_LIST_REQUESTED = 'FEATURE_LIST_REQUESTED'
export const FEATURE_LIST_FETCHED = 'FEATURE_LIST_FETCHED'
export const FEATURE_LIST_FAILED = 'FEATURE_LIST_FAILED'

// EXAMPLES
export const DATA_LIST_REQUESTED = 'DATA_LIST_REQUESTED'
export const DATA_LIST_FETCHED = 'DATA_LIST_FETCHED'
export const DATA_LIST_FAILED = 'DATA_LIST_FAILED'


export const APP_SIDEBAR_TOOGLE = 'APP_SIDEBAR_TOOGLE'